# Generated by Django 2.1.5 on 2019-01-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=None, max_length=100, unique=True, verbose_name='Project Name')),
                ('client_name', models.CharField(default=None, max_length=100, verbose_name='Client Name')),
                ('client_department', models.CharField(default=None, max_length=100, verbose_name='Client Department')),
                ('client_phone', models.CharField(default=None, max_length=100, verbose_name='Client Phone')),
                ('project_total_hours', models.IntegerField(default=10, verbose_name='Total Hours')),
                ('project_comments', models.TextField(blank=True, max_length=25000, verbose_name='Comments')),
                ('project_notes', models.TextField(blank=True, max_length=25000, verbose_name='Notes')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
